### PR TITLE
v0.40.0 – Rearranging styles and updating onto f-utils package

### PR DESCRIPTION
**Pull request by ashleynolan**
### Changed
- Moved base header styles into `_header.scss` file for better separation
- Changed utils dependencies onto `@justeat/f-utils` module rather than using `kickoff/utils`
- Updated package dependencies

### CODE REVIEW

**Comment by DamianMullins** [comment]
I *think* the builds are failing because of the node 10 change in the Travis config, i saw the same thing las week. Not quite sure what the issue is exactly though..

**Comment by ashleynolan** [comment]
@DamianMullins Yeh – I think it might be because I updated this PR onto Danger v4.  I'll merge this and take a look at the Danger issue separately.

**Comment by DamianMullins** [comment]
@ashleynolan I'm not sure that is the issue; I [updated `f-dom` last week](https://github.com/justeat/f-dom/pull/11/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34) to use Node v10 and Danger v4 and the build ran fine?

**Comment by ashleynolan** [comment]
@DamianMullins I'll take a look – seems all other repos are working so when I put in the Menulog PR for this module will try and fi this at the same time.  Doesn't seem to be any issue with Danger v4 on the other repos that I've tried it on…

**Pull request merged**
