### PR TITLE
v0.21.2 - Fix incorrect link text

### PR DESCRIPTION
**Pull request by martincostello**
Change link text for `contactPreferences` to match UK production.

image

### CODE REVIEW

**Comment by ashleynolan** [comment]
@martincostello Just fixed Travis and rebuilding now.  Was using old credential for PR checks.

**Comment by ashleynolan** [comment]
Couple of points that the CI build will pick up on:

- Will need to update CHANGELOG
- `Package.json` version will need to be updated to make a new release
- PR title should start with the new version number (so v1.2.0 or whatever it is)

**Comment by martincostello** [comment]
So every PR is considered to be a release, things can't be batched?

**Comment by DamianMullins** [comment]
Yes, that is the way we have been working @martincostello

**Comment by ashleynolan** [comment]
Multiple changes can be made in one version if they make sense together.  Major version jumps usually have multiple big changes grouped together.

**Comment by martincostello** [comment]
I wasn't intending to necessarily release this as there's other questions in the associated JIRA that might mean there's more changes to make before a new release would be considered worth doing, but if that's the process you're using.

**Pull request merged**
